# Generated by Django 5.2 on 2025-05-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Ид пользователя')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive'), ('BL', 'Blocked')], default='AC', max_length=50)),
            ],
            options={
                'verbose_name': 'Пользователя хостинга',
                'verbose_name_plural': 'Пользователи хостинга',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('preview', models.ImageField(upload_to='video/previews', verbose_name='Обложка видео')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('duration', models.DurationField(verbose_name='Длительность видео')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video_hosting.user', verbose_name='Автор видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('watching_at', models.PositiveIntegerField(null=True, verbose_name='Точка просмотра видео')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_hosting.video', verbose_name='Видео')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video_hosting.user', verbose_name='Зритель')),
            ],
            options={
                'verbose_name': 'Просмотренное Видео',
                'verbose_name_plural': 'Просмотренное Видео',
            },
        ),
    ]
