# Generated by Django 5.2 on 2025-05-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedvideo',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='video_hosting.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='watchedvideo',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watched_videos', to='video_hosting.user', verbose_name='Зритель'),
        ),
    ]
