# Generated by Django 5.2 on 2025-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0005_alter_watchedvideo_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='master_playlist',
            field=models.FileField(null=True, upload_to='video/master_playlists/', verbose_name='Мастер плейлист'),
        ),
        migrations.AddField(
            model_name='video',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to='videos/previews/', verbose_name='Обложка видео'),
        ),
    ]
