# Generated by Django 5.2 on 2025-05-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0006_video_master_playlist_video_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('playlist_file', models.FileField(null=True, upload_to='videos/variants/', verbose_name='Варианты видео')),
                ('resolution', models.PositiveIntegerField(verbose_name='Разрешение')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='video_hosting.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
