# Generated by Django 5.2 on 2025-05-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0007_videovariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='Точка просмотра видео')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='video_hosting.video', verbose_name='Видео')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watched_videos', to='video_hosting.user', verbose_name='Зритель')),
            ],
            options={
                'verbose_name': 'Просмотренное Видео',
                'verbose_name_plural': 'Просмотренное Видео',
            },
        ),
        migrations.DeleteModel(
            name='WatchedVideo',
        ),
    ]
