# Generated by Django 5.2 on 2025-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0008_videotracker_delete_watchedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='master_playlist',
            field=models.FileField(null=True, upload_to='videos/master_playlists/', verbose_name='Мастер плейлист'),
        ),
    ]
