# Generated by Django 5.2 on 2025-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0009_alter_video_master_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/original_files/', verbose_name='Видео'),
        ),
        migrations.DeleteModel(
            name='VideoVariant',
        ),
    ]
