# Generated by Django 5.2 on 2025-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0011_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_dir_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название директории HLS'),
        ),
    ]
