# Generated by Django 5.2 on 2025-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0012_video_hls_dir_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_creation_time',
            field=models.DateTimeField(null=True, verbose_name='Дата создания видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_dir_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название директории HLS'),
        ),
    ]
