# Generated by Django 5.2 on 2025-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0013_video_video_creation_time_alter_video_hls_dir_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='videos/original_files/', verbose_name='Видео'),
        ),
    ]
