# Generated by Django 5.2 on 2025-05-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0014_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_creation_time',
        ),
    ]
