# Generated by Django 5.2 on 2025-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0016_user_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hash',
            field=models.CharField(max_length=150, null=True, verbose_name='Хеш видео'),
        ),
    ]
