# Generated by Django 5.2 on 2025-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0018_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hash',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Хеш видео'),
        ),
    ]
