# Generated by Django 5.2 on 2025-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0020_alter_video_hls_dir_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_dir_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название директории HLS'),
        ),
    ]
